### ISSUE TITLE
Helm test fails if the lookup function is used in helmcharts

### ISSUE THREAD

**Issue by kirankumarcelestial** [lrills/helm-unittest#108]
Helm 3, has a lookup function that can be used to lookup cluster value, however when used this function within helm charts, the unittest fails with 'function "lookup" not defined'

for example:
the line used inside the helm charts passes helm lint, helm template, helm install --dry-run, but fails with helm unittest.

{{- $dataPvc  := (lookup "v1" "pvc" .Release.Namespace .Values.persistence.data.existingClaim) }}

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
