### ISSUE TITLE
Migration to Python/Go unittest

### ISSUE THREAD

**Issue by mik-laj** [lrills/helm-unittest#110]
Hello,

In the Apache Airflow project, we made the decision to migrate to Python tests supported by a small function that is used to generate templates.
Discussion: https://github.com/apache/airflow/issues/11657
Related PR:
https://github.com/apache/airflow/pull/11693
https://github.com/apache/airflow/pull/11827

I even prepared a script that converts helm-unittest tests to Python tests. The script has no coverage for all Helm-unittest features, but it was sufficient in our case. If someone wants to use it, there is a chance that they will have to add some features, but it shouldn't be difficult. 
Script: https://gist.github.com/mik-laj/3ae253d5394b34447dcbd426fd19b389

Alternatively, you can use the [terratest](https://blog.gruntwork.io/automated-testing-for-kubernetes-and-helm-charts-using-terratest-a4ddc4e67344) if you prefer Go. In this case, we don't have an auto-migration tool.
 
Best regards,
Kamil Breguła

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
