### ISSUE TITLE
Support subchart

### ISSUE THREAD

**Issue by morvencao** [lrills/helm-unittest#23]
Seems `helm-unittest` doesn't support `subchart`.
I tried two methods to workaround this, still no good with issue.

**1. Add `tests` directory to subchart and create test file there**
The whole chart directory resemble:
```
mychart/
    Chart.yaml
    values.yaml
    templates/
        _helpers.tpl
        deployment.yaml
        service.yaml
    charts/
        mysubchart/
            Chart.yaml
            templates/
               deployment.yaml
               service.yaml
            tests/
               deployment_test.yaml
               service_test.yaml
```
And run `unittest` in subchart:
```
helm unittest mychart/charts/mysubchart
```

Error message I got:
```
### Chart [ mysubchart ] mysubchart

 FAIL  test deployment	mysubchart/tests/deployment_test.yaml
	- should work
		Error: render error in "mysubchart/templates/deployment.yaml": template: mysubchart/templates/deployment.yaml:12:40: executing "mysubchart/templates/deployment.yaml" at <{{template "mychart.co...>: template "mychart.configmap.checksum" not defined
```
Because I have embed named template in `mysubchart/templates/deployment.yaml` which defined in parent chart `mychart/_helpers.tpl`.

------------------------

**2. Add all subchart test file to `tests` directory of parent chart.**
The whole chart directory resemble:
```
mychart/
    Chart.yaml
    values.yaml
    templates/
        _helpers.tpl
        deployment.yaml
        service.yaml
    tests/
       mysubchart_deployment_test.yaml
       mysubchart_service_test.yaml
    charts/
        mysubchart/
            Chart.yaml
            templates/
               deployment.yaml
               service.yaml               
```

In the test suite of `mychart/tests/mysubchart_deployment_test.yaml`,  `template` refer the respective template file of `mysubchart`, like this:
```
suite: test mysubchart deployment
templates:
  - ../charts/mysubchart/template/deployment.yaml
tests:
...
```
And then run `helm unittest` in parentchart:
```
helm unittest mychart
```

Error message I got:
```
FAIL  test mysubchart deployment	mychart/tests/mysubchart_deployment_test.yaml
	- Execution Error:
		template file `templates/../charts/mysubchart/templates/deployment.yaml` not found in chart

 FAIL  test mysubchart service	mychart/tests/mysubchart_service_test.yaml
	- Execution Error:
		template file `templates/../charts/mysubchart/templates/service.yaml` not found in chart
```

Actually, the template file `templates/../charts/mysubchart/templates/deployment.yaml` and `templates/../charts/mysubchart/templates/service.yaml` do exist.

------------------------------------------------

### Expected behivour, create test files in method 1: 
**Directly run `unittest` in parent chart, it will include all `unittest` cases defined in subchart.**

**Comment by morvencao** [comment]
Aligning behavior with `helm` will be OK, I think.  For example, keep `named template` global.

**Comment by lrills** [comment]
Hi, v0.1.2 is released and should work with subchart now!
Check [README](https://github.com/lrills/helm-unittest#tests-within-subchart) and the [example](https://github.com/lrills/helm-unittest/tree/master/__fixtures__/with-subchart) for details. And feel free to reopen this if any problem met.
