### ISSUE TITLE
Assertion type `isApiVersion` is invalid, which should be `isAPIVersion `

### ISSUE THREAD

**Issue by morvencao** [lrills/helm-unittest#24]
Have gone through the doc and ind assertion type `isApiVersion` in:
https://github.com/lrills/helm-unittest/blob/master/DOCUMENT.md#assertion-types

When run `helm unittest`, got the error:
```
 FAIL  	mychart/tests/service_test.yaml
	- Execution Error:
		Assertion type `isApiVersion` is invalid
```
Actually it should be `isAPIVersion `, find it in test file example:
https://raw.githubusercontent.com/lrills/helm-unittest/master/__fixtures__/basic/tests_failed/deployment_test.yaml

So this is a doc issue.

**Comment by lrills** [comment]
Thanks! Forget to update the legacy doc. 😅
