### ISSUE TITLE
Take dependency on Helm wherever possible

### ISSUE THREAD

**Issue by jdolitsky** [lrills/helm-unittest#25]
This project should import "k8s.io/helm" so there is a higher confidence that values are being parsed identically to how Helm CLI does it.

These method copies such as `MergeValues` should be able to be safely removed https://github.com/lrills/helm-unittest/blob/436447d3bcc47be1ed51d66bc7a21dec7d97262e/unittest/valueutils/valueutils.go#L194

**Comment by jdolitsky** [comment]
Some stuff will need to be copy-pasted definitely! I would start w helm v2.8.2, integrate as much as possible and see what breaks. Even if my tests are all green, I would be hesitant to rely on the tool in a CI environment if the yaml templating didnt work exactly like helm.

**Comment by lrills** [comment]
Oh, the rendering part do use helm itself that can be relied on (now 2.7.2, maybe bump to 2.8 next patch). But most earlier part of code did copy paste quite a things, mostly for simulating cli behavior in yaml, I would have a check on that part!
https://github.com/lrills/helm-unittest/blob/2d45bb580e222bf28bac06dc41b8b75daebdba63/unittest/test_job.go#L14-L17
