### ISSUE TITLE
Alpine linux untt: no such file or directory

### ISSUE THREAD

**Issue by vliubezny** [lrills/helm-unittest#41]
```
bash-4.3# ls -al /root/.helm/plugins/helm-unittest/untt
-rwxr-xr-x    1 root     root       8995465 Jun  5 17:37 /root/.helm/plugins/helm-unittest/untt
bash-4.3# helm unittest -h
Error: fork/exec /root/.helm/plugins/helm-unittest/untt: no such file or directory
```
`untt` is built with dynamic linking against _gnu libc_ which is missing on some linux distros, e.g. alpine.

**Comment by lrills** [comment]
Hi @vliubezny, are you using it in the docker container? I'm thinking instead of providing builds for all distros, it would be better to have a official docker repo and you can use it like:

```dockerfile
FROM xxx/helm-unittest:alpine
```
Would this help?

**Comment by vliubezny** [comment]
Hi @lrills! Yes, I'm using docker with custom image, i.e. helm with multiple plugins + kubectl + azure-cli + python scripts to build and install charts into azure k8s cluster. I don't find it convenient to use `xxx/helm-unittest:alpine` as base image in this case.

Nevertheless such image implies _gnu libc_ free build of `untt` or some extra setup for alpine image. I could apply same solution for my custom alpine image.
