### ISSUE TITLE
Templates in subdirectories fail to load

### ISSUE THREAD

**Issue by snooc** [lrills/helm-unittest#44]
I have a helm chart that uses subdirectories to organize some different services (instead of subcharts):

```
templates
- web-service
-- deployment.yaml
- database
-- stateful-set.yaml
```

If I create a test suite similar to:

```
suite: test stuff
templates:
- web-service/web-deployment.yaml
tests:
...
```

I get an error:

```
$ helm unittest -f 'tests/*-test.yaml' .

### Chart [ test-chart ] .

 FAIL  TLS enabled mounts    tests/first-test.yaml
    - Execution Error:
        template file `templates/web-service/web-deployment.yaml` not found in chart
```

If I modify the test suite to reference the template at `web-deployment` with no subdir, then the test runs, but fails again while loading another file to create a checksum. 

```
suite: test stuff
templates:
- web-deployment.yaml
tests:
...
```

```
$ helm unittest -f 'tests/*-test.yaml' .

### Chart [ test-chart ] .

 FAIL  TLS enabled mounts	tests/first-test.yaml
	- some test
		Error: render error in "immuta/templates/web/web-deployment.yaml": template: test-chart/templates/web/web-deployment.yaml:37:28: executing "test-chart/templates/web/web-deployment.yaml" at <include (print $.Tem...>: error calling include: template: no template "test-chart/templates/web/web-secret.yaml" associated with template "gotpl"
```

I'm willing to submit a PR, but I figured I'd file an issue before digging into the code base.

**Comment by danhawkins** [comment]
I'm hitting this issue also, is there a fix?

**Comment by ozzann** [comment]
It seems it's not fixed but the simple workaround could be avoid using subdirectories and store all the templates at one directory just add some prefixes to file names. Or to keep the current structure you can do the same but copy all the files from subdirectories to another folder before running helm unittest. Hope it makes sense.

**Comment by sroze** [comment]
Same behaviour in here 👍

**Comment by sarialem** [comment]
I see this is still open, and I'm still facing this issue when testing templates in subdirectories

**Comment by quintush** [comment]
@sarialem, best to use this fork https://github.com/quintush/helm-unittest.
It contains fixes, including templates with subdirectories.

Greetings.

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
