### ISSUE TITLE
debug/verbose output

### ISSUE THREAD

**Issue by benzvan** [lrills/helm-unittest#48]
I'm getting the following result:

``` 
FAIL  test deployment	ratpack/tests/deployment_test.yaml
	- should work
		Error: yaml: line 84: found character that cannot start any token
```

But there is no indication which file has a problem and if that is before or after parsing/merging/templating them. It would be great to have more verbose output as an option to help locate these problems.

**Comment by benzvan** [comment]
I managed to find my specific problem and it was pretty complex. The best-case for this would be that the error would show the contents of the invalid line for easier debugging. I also tested the chart with a --dry-run of helm and got a similar error. I'll also report this as a bug in this version of helm.

**Comment by libkad** [comment]
I was just about to open the same issue.

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
