### ISSUE TITLE
TAPs or XUNIT output

### ISSUE THREAD

**Issue by TD-4242** [lrills/helm-unittest#51]
Would be very nice if I could injest the test output into my CI server (Jenkins) to run build/test reports on.

**Comment by quintush** [comment]
@TD-4242 , i have added (multiple) test output for CI server.
Since it's not merged into this repo, you can download a version from my forked repo: https://github.com/quintush/helm-unittest/releases

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
