### ISSUE TITLE
Feature enhancement: containsOnce

### ISSUE THREAD

**Issue by benzvan** [lrills/helm-unittest#52]
I just ran into a test condition where I was using contains to test that my config was present because I didn't care about the rest of the config. Now I'm wishing there was a "containsOnce" because my array had two copies of the configuration I needed, which resulted in an invalid chart.

Expected outcome:
```
asserts:
  - contains: 
      content: a
```
on
```
[ a, a, b, c ]
```
returns true

but

```
asserts:
  - containsOnce: 
      content: a
```
on
```
[ a, a, b, c ]
```
returns false

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
