### ISSUE TITLE
Render error when template uses include of a template filename

### ISSUE THREAD

**Issue by luxi2001** [lrills/helm-unittest#53]
unittest fails when the template includes a file to create a checksum as described [here](https://github.com/technosophos/k8s-helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change)

```
 FAIL  test deployment	tests/deployment_test.yaml
	- should work
		Error: render error in "fsjetty/templates/deployment.yaml": template: fsjetty/templates/deployment.yaml:18:28: executing "fsjetty/templates/deployment.yaml" at <include "../template...>: error calling include: template: no template "../templates/configmap.yaml" associated with template "gotpl"
```

deployment_test.yaml:
```
suite: test deployment
templates:
  - deployment.yaml
tests:
...
```
where deployment.yaml has:
```
annotations:
  checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```

**Comment by davidkarlsen** [comment]
@lrills any comment?

**Comment by davidkarlsen** [comment]
@lrills ping

**Comment by mikelorant** [comment]
This is solvable by including the configmap yaml file in templates section. Example:
```
suite: test
templates:
  - deployment.yaml
  - configmap.yaml
```

**Comment by davidkarlsen** [comment]
Great - thanks - that worked!

**Comment by lrills** [comment]
It seem to solved, but maybe we should consider not to filter files while rendering.

**Comment by floretan** [comment]
Thanks, ran into this today and was happy to find the solution documented here.
