### ISSUE TITLE
Add ability to test dependent charts defined in requirements.yaml

### ISSUE THREAD

**Issue by markperdue** [lrills/helm-unittest#65]
Hello,

Is it possible to define a test file that supports checking the resolved values that would apply to charts pulled into helm through 'helm dependency update' prior to running unittests?

Suppose I have a chart called `my-app-implementation` that has a requirements.yaml file that includes a base chart `my-app`. The base chart for `my-app` would include its values.yaml file as normal and suppose it sets a values.yml stanza as

```yaml
deployment:
  resources:
    limits:
      cpu: 100m
```
which leads that chart to set the proper cpu limit for a `Deployment` object. When the `my-app-implementation` chart runs suppose I set its value.yaml file to the following to override that dependent chart's value:

```yaml
my-app:
  deployment:
    resources: {}
```

which would lead Helm to override the cpu limit stanza that would have been applied to the nested chart `my-app`

The issue I am seeing is that since the nested chart only exists as a tarball under the `charts/` directory of `my-app-implementation` my test file within the implementation chart is unable to find the `deployments.yaml` file as it only exists within the `my-app` chart under that charts 'templates/` directory

Is it possible to use `unittest` to assert that a cpu limit must exist in the resulting deployment object for this nested `my-app` chart by defining something only in a test file within the `my-app-implementation` chart?

**Comment by markperdue** [comment]
The goal is to make sure an operator cannot easily create an umbrella chart that includes base charts that themselves set good practices around requiring things like resource limites/requests and health checks but where the operator then tries to bypass those things by overriding the stanzas through the implementation chart's values.yaml file

**Comment by lrills** [comment]
@markperdue it actually works with tests files contained subchart with `-with-subchart` flag set to true (which is by default but missed in doc), please check is this fixture fits your need: 
https://github.com/lrills/helm-unittest/tree/master/__fixtures__/with-subchart

**Comment by rockholla** [comment]
I also came upon this need today. Just to clarify, and I believe this is the same thing that @markperdue would like is to have the ability to test templates that are ultimately rendered from a subchart, but I believe that's currently not possible:

Here's `my-chart` which has `my-subchart` as a dependency and pulled in to the charts directory:

```
Chart.yaml
README.md
charts
  my-subchart
    ...
    templates
      deployment.yaml
requirements.yaml
templates
tests
  defaults_test.yaml
values.yaml
```

Here's the `tests/defaults_test.yaml` file:

```
---
suite: defaults
templates:
  - deployment.yaml
tests:
  - it: should default to Deployment
    asserts:
      - template: deployment.yaml
        isKind:
          of: Deployment
```
Now, running `helm unittest .` or `helm unittest --with-subchart .` both produce:

```
### Chart [ my-chart ] /charts/my-chart

 FAIL  defaults	my-chart/tests/defaults_test.yaml
	- Execution Error:
		template file `templates/deployment.yaml` not found in chart


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 1 errored, 0 passed, 1 total
Tests:       0 passed, 0 total
Snapshot:    0 passed, 0 total
Time:        91.543ms
```

The deployment.yaml template exists in the subchart, but it doesn't appear there's any way to validate anything rendered from a subchart, only things rendered from the current chart. I would think this would be a pretty common need and something that others would expect to be able to do, so I'm going to work on a fix for this in a fork and submit as PR back.

**Comment by sylvainOL** [comment]
Hello, would love to have that for:

* charts put in requirements.yml (see if they are created with the proposed values)
* charts put in "charts" folder (same reason)

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
