### ISSUE TITLE
Ability for "fail" assertions

### ISSUE THREAD

**Issue by Rajiwan** [lrills/helm-unittest#82]
In JUnit and other testing languages, you can create tests that EXPECT/validate failure conditions.  I am writing TPL code for my Helm charts, and if user does not provide required parameters, I am calling TPL "fail" method to cause a chart rendering error, thus preventing (accidental/partial) deployment.  I.e. 

    {{- cat "ERROR: Required parameter (" $param ") is not defined" | **fail** -}}

I want to create a test that validates if parameter is not defined, then render error should be expected, and if template somehow SUCCEEDS, then this is an error, which should fail the test.  So I guess I am looking for something like:

  - it: if PVC is not defined, it should fail
    asserts:
      - shouldFail:

The same would be true for the built-in "required" (which calls "fail" under the hood) method, i.e.:

   someParam: {{ required "Please define X" .Values.X }}

this generates a render error, and I would like to have a test "if notDefined(X) then expectError".

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
