### ISSUE TITLE
Testing empty templates

### ISSUE THREAD

**Issue by omerlh** [lrills/helm-unittest#83]
Assuming I have the following helm template file:
```
{{- if .Values.something }}
<some Kubernetes manifest file>
 {{- end }}
```
I  want to test that the object exists or not based on `something`. This is not possible today because the tests are failing with the following error:
```
        - not includes identity when identity is not set

                - asserts[0] `notEqual` fail

                        Error:
                                assertion.template must be given if testsuite.templates is empty
```

**Comment by amasucci** [comment]
Hi omerlh,

have you tried with:
```yaml 
tests:
  # default state
  - it: should pass
    asserts:
      - hasDocuments:
          count: 0
```
I found it here:
https://github.com/lrills/helm-unittest/blob/master/DOCUMENT.md

**Comment by omerlh** [comment]
No, but I can try that - guess this will work only if there is one document in test...

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
