### ISSUE TITLE
Even the negative test cases are getting passed  with warning

### ISSUE THREAD

**Issue by aman1989v** [lrills/helm-unittest#85]
Hi Team, 

There is an unusual scenario where If I am givign any negative test case, it should fail right? 
However it is getting passed with a warning. **"Warning: Building values map for chart 'uma'. Skipped value (map[]) for 'image', as it is not a table."** 

Could you please let me know what mistake I am making.

Below is the snippet. 

helm unittest uma

### Chart [ uma ] uma

2019/08/29 04:36:05 Warning: Building values map for chart 'uma'. Skipped value (map[]) for 'image', as it is not a table.
 PASS  test deployment of prometheus    uma/tests/deployment_prometheus_test.yaml
2019/08/29 04:36:05 Warning: Building values map for chart 'uma'. Skipped value (map[]) for 'image', as it is not a table.
 PASS  test deploy,ent  uma/tests/deployment_apmia_test.yaml

Charts:      1 passed, 1 total
Test Suites: 2 passed, 2 total
Tests:       4 passed, 4 total
Snapshot:    0 passed, 0 total
Time:        10.129211ms

**Comment by aman1989v** [comment]
Hi, 
I would like to tell that I have found the issue but not the reason why it is happening. 
I found that in my values.yaml file there is a key with name "image" when I change the name of it to any other name, it is working. 
<code> image: dockerimage:v1 </code>
But it should work with the "image" as I cannot change the key name.
Could you please let me know the solution. 

Thanks, 
Aman

**Comment by aman1989v** [comment]
Could you please answer my question ?

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
