### ISSUE TITLE
Helm v3 Compatibility

### ISSUE THREAD

**Issue by dansiviter** [lrills/helm-unittest#87]
It seems this doesn't work with the latest v3-beta3 build failing with the following on install:
```
$ helm plugin install https://github.com/lrills/helm-unittest
Downloading https://github.com/lrills/helm-unittest/releases/download/v0.1.5/helm-unittest-macos-0.1.5.tgz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   620    0   620    0     0   2668      0 --:--:-- --:--:-- --:--:--  2660
100 3119k  100 3119k    0     0   466k      0  0:00:06  0:00:06 --:--:--  612k
Preparing to install into The Kubernetes package manager
...
Use "helm [command] --help" for more information about a command./plugins/helm-unittest: name too long
Failed to install helm-unittest
For support, go to https://github.com/kubernetes/helm
Error: plugin install hook for "unittest" exited with error
```

It does appear to be registered with Helm:
```
$ helm plugin list
NAME            VERSION DESCRIPTION                                                                         
unittest        0.1.5   Unit test for helm chart in YAML with ease to keep your chart functional and robust.
```

But any time you use it it fails:
```
$ helm unittest .
Error: fork/exec /Users/john.doe/Library/helm/plugins/helm-unittest/untt: no such file or directory
```

*Environment*
* OS: Mac
* Helm:
```
version.BuildInfo{Version:"v3.0.0-beta.3", GitCommit:"5cb923eecbe80d1ad76399aee234717c11931d9a", GitTreeState:"clean", GoVersion:"go1.12.9"}
```

**Comment by anikin-aa** [comment]
Facing similar issue +1

**Comment by dansiviter** [comment]
@anikin-aa Yea, looks good with helm 3.0.0-rc.3. Sorry for delay responding.

**Comment by stefancplace** [comment]
I would really appreciate Helm v3 compatibility as well, 
@lrills Can we get a new release of this please?

**Comment by sokoow** [comment]
facing same issue here

**Comment by mmornati** [comment]
Any news about this problem? Is there any workaround on this issue?

**Comment by mmornati** [comment]
In the end I found how to install it and where is the problem. The `install-binary.sh` script is using the `helm home` command which is not existing anymore.
I modified it in the `/tmp` folder and the install worked well.
![image](https://user-images.githubusercontent.com/139323/76325157-4d2d4000-62e7-11ea-9d4c-09460cd31189.png)

Then in the script just change the line with `HELM_PLUGIN_PATH` with
```
: ${HELM_PLUGIN_PATH:="$(helm env | grep HELM_PLUGINS | awk -F '=' '{print $2}' | sed 's/\"//g')/helm-unittest"}
```
I guess the bash command can be improved :) And I don't know if it is working in anything else than MacOsx

I can push a PR if you want and if it is working for someone else.

**Comment by vazhem** [comment]
workaround for installation of the plugin for Helm 3
```
wget  https://github.com/lrills/helm-unittest/releases/download/v0.1.5/helm-unittest-linux-0.1.5.tgz
mkdir -p ${HOME}/.local/share/helm/plugins/unittest
tar xzf  helm-unittest-linux-0.1.5.tgz -C ${HOME}/.local/share/helm/plugins/unittest
```

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
