### ISSUE TITLE
Support Capabilities

### ISSUE THREAD

**Issue by drpebcak** [lrills/helm-unittest#88]
It would be awesome to be able to set `Capabilities` when running tests to ensure that a chart renders like we expect with different versions of k8s, api groups/versions, etc.

See Helm Capabilities section here for more info on what Helm can do with this: https://github.com/helm/helm/blob/master/docs/chart_template_guide/builtin_objects.md

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
