### ISSUE TITLE
support for 2.16.x new deepCopy function

### ISSUE THREAD

**Issue by TD-4242** [lrills/helm-unittest#96]
```
 FAIL  chart tester	tests/chart_test.yaml
	- should render a basic deployment
		Error: parse error in "chart/templates/chart.yaml": template: chart/templates/chart.yaml:7: function "deepCopy" not defined
```

**Comment by quintush** [comment]
@TD-4242, during the feature add-ons, i have updated the libraries, please verify if the deepCopy function is working accordingly.
I would also help if you can send me an example, so i can add the example to the testscenario's.
Always better to have prove in the source code. :)

**Comment by gandhiprachi** [comment]
@quintush  - what's the status of Numerous features and bugfixes #105?

**Comment by quintush** [comment]
> @quintush  - what's the status of Numerous features and bugfixes #105?

[Best to use my creatief release, fully backwards compatible with additional features] (https://github.com/quintush/helm-unittest/releases/tag/v0.2.0)

I have closed my pullrequest as it was blocking my development. All features and bugfixes where already tested in my release.

**Comment by gandhiprachi** [comment]
thanks for the headsup @quintush !

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
