### ISSUE TITLE
Versioned url never used

### ISSUE THREAD

**Issue by brendarearden** [lrills/helm-unittest#97]
https://github.com/lrills/helm-unittest/blob/695dac23a25c1e39836cf3c8273fab6baa924f69/install-binary.sh#L72

The versioned url is being set to the variable `url` but all the `curl` and `wget` commands only reference `latest_url` so the versioned url is never being used to download the correct binary

**Comment by quintush** [comment]
@brendarearden, i have updated the url to use latest_url. 
Since it's not merged into this repo, you can download a version from my forked repo: https://github.com/quintush/helm-unittest/releases

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
