### ISSUE TITLE
name too long error

### ISSUE THREAD

**Issue by developer-guy** [lrills/helm-unittest#98]
> version.BuildInfo{Version:"v3.0.2", GitCommit:"19e47ee3283ae98139d98460de796c1be1e3975f", GitTreeState:"clean", GoVersion:"go1.13.5"}

i am using helm version 3 on macOS , when i try to install this plugin i am getting an error : 

> Use "helm [command] --help" for more information about a command./plugins/helm-unittest: name too long
> Failed to install helm-unittest
> For support, go to https://github.com/kubernetes/helm
> Error: plugin install hook for "unittest" exited with error

**Comment by mmornati** [comment]
I'm getting the same error. It seems only related to the full path I guess. Is there any way to work around the problem?

**Comment by mmornati** [comment]
I guess it is a duplicated issue. All is already discussed on #87

**Comment by AntonClark** [comment]
Try to use Long Path Tool, it really can help you with 

that.

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).
